"use client";

import { FormEvent, useState } from "react";
import { delayBand, type DisruptionType } from "@/lib/community-insights";

const reasons = ["operational", "technical", "crew", "weather", "air_traffic_control", "security", "other", "unspecified"];
const resolutions = [["cash_payment", "Cash payment"], ["voucher", "Voucher"], ["refund", "Refund"], ["rerouting", "Replacement flight"], ["expenses", "Expenses repaid"], ["no_offer", "No offer"], ["not_resolved", "Still not resolved / Momo did not help"], ["other", "Other"]] as const;
const unresolvedReasons = [["airline_did_not_reply", "The airline did not reply"], ["airline_refused", "The airline refused"], ["needed_more_evidence", "I needed evidence I did not have"], ["momo_misunderstood", "Momo misunderstood my situation"], ["different_help_needed", "I needed different help"], ["other", "Another reason"]] as const;

export function CommunityInsights({ disruptionType, delayMinutes }: { disruptionType: DisruptionType; delayMinutes: number | null }) {
  const [airline, setAirline] = useState(""); const [reasonCategory, setReasonCategory] = useState("unspecified"); const [message, setMessage] = useState(""); const [research, setResearch] = useState<{ summary: string; source_urls: string[] } | null>(null);
  const check = async (requestResearch = false) => {
    setMessage(""); setResearch(null);
    try {
      const response = await fetch("/api/insights", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ airline, disruptionType, delayMinutes, reasonCategory, requestResearch }) });
      const data = await response.json();
      if (!response.ok) return setMessage(data.error ?? data.message ?? "Momo could not check that yet.");
      setMessage(data.community ? `${data.message} Offers seen: ${data.community.offered_low ?? "not enough data"} to ${data.community.offered_high ?? "not enough data"}${data.community.common_resolution ? `. Common resolution: ${data.community.common_resolution.replaceAll("_", " ")}` : ""}` : data.message);
      if (data.research) setResearch(data.research);
    } catch { setMessage("Momo could not reach the insights service. Please check your connection and try again."); }
  };
  return <section className="community-panel"><h2>What has Momo seen in similar cases?</h2><p>These are anonymous patterns, never a promised result. Momo only shows a pattern after at least 10 similar outcomes.</p><div className="community-fields"><label>Airline<input value={airline} onChange={(event) => setAirline(event.target.value)} maxLength={80} placeholder="e.g. British Airways" /></label><label>Airline&apos;s reason<select value={reasonCategory} onChange={(event) => setReasonCategory(event.target.value)}>{reasons.map((reason) => <option key={reason} value={reason}>{reason.replaceAll("_", " ")}</option>)}</select></label></div><div className="community-actions"><button className="secondary" onClick={() => check()}>Check anonymous patterns</button><button className="text-button" onClick={() => check(true)}>Check official sources</button></div>{message && <p className="insight-message" role="status">{message}</p>}{research && <div className="official-note"><b>Official-source note</b><p>{research.summary}</p>{research.source_urls.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer">Open source &rarr;</a>)}</div>}<small>Current delay band: {delayBand(delayMinutes).replaceAll("_", " ")}. Live checks are limited to keep costs low.</small></section>;
}

export function OutcomePanel({ disruptionType, delayMinutes }: { disruptionType: DisruptionType; delayMinutes: number | null }) {
  const [airline, setAirline] = useState(""); const [reasonCategory, setReasonCategory] = useState("unspecified"); const [resolutionType, setResolutionType] = useState("cash_payment"); const [unresolvedReason, setUnresolvedReason] = useState(""); const [requestedAmount, setRequestedAmount] = useState(""); const [offeredAmount, setOfferedAmount] = useState(""); const [acceptedAmount, setAcceptedAmount] = useState(""); const [currency, setCurrency] = useState("GBP"); const [customCurrency, setCustomCurrency] = useState(""); const [optedIn, setOptedIn] = useState(false); const [message, setMessage] = useState("");
  const selectedCurrency = currency === "OTHER" ? customCurrency.trim().toUpperCase() : currency;
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(""); if (!/^[A-Z]{3}$/.test(selectedCurrency)) return setMessage("Choose a three-letter currency code, such as GBP or PEN."); try { const response = await fetch("/api/outcomes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ airline, disruptionType, delayMinutes, reasonCategory, resolutionType, unresolvedReason, requestedAmount, offeredAmount, acceptedAmount, currency: selectedCurrency, optedIn, shareInTicker: false }) }); const data = await response.json(); setMessage(data.message ?? data.error ?? "Momo could not save that outcome."); } catch { setMessage("Momo could not reach the outcome service. Please check your connection and try again."); } };
  const moneyField = (label: string, value: string, onChange: (value: string) => void) => <label>{label} ({selectedCurrency || "currency"})<input type="number" min="0" max="50000" step="0.01" value={value} onChange={(event) => onChange(event.target.value)} /></label>;
  return <section className="outcome-panel"><h2>Did the airline resolve your case?</h2><p>If you choose to share, Momo stores only these anonymous outcome fields. It never shares your email, booking, documents, message, or this claim.</p><form onSubmit={submit}><div className="community-fields"><label>Airline<input value={airline} onChange={(event) => setAirline(event.target.value)} required maxLength={80} /></label><label>Reason category<select value={reasonCategory} onChange={(event) => setReasonCategory(event.target.value)}>{reasons.map((reason) => <option key={reason} value={reason}>{reason.replaceAll("_", " ")}</option>)}</select></label><label>Solution<select value={resolutionType} onChange={(event) => setResolutionType(event.target.value)}>{resolutions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>{resolutionType === "not_resolved" && <label className="city-field">What stopped this being resolved?<select value={unresolvedReason} onChange={(event) => setUnresolvedReason(event.target.value)} required><option value="">Choose one</option>{unresolvedReasons.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><small>Please choose a category only — do not add names, booking references, or message text.</small></label>}<div className="money-fields">{moneyField("Asked for", requestedAmount, setRequestedAmount)}{moneyField("Offered", offeredAmount, setOfferedAmount)}{moneyField("Accepted", acceptedAmount, setAcceptedAmount)}</div><label className="city-field">Currency<select value={currency} onChange={(event) => setCurrency(event.target.value)}><option value="GBP">GBP (UK pound)</option><option value="EUR">EUR (euro)</option><option value="USD">USD (US dollar)</option><option value="CAD">CAD (Canadian dollar)</option><option value="SGD">SGD (Singapore dollar)</option><option value="OTHER">Other currency</option></select></label>{currency === "OTHER" && <label className="city-field">Three-letter currency code<input value={customCurrency} onChange={(event) => setCustomCurrency(event.target.value.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 3))} placeholder="e.g. PEN" maxLength={3} required /></label>}<label className="opt-in"><input type="checkbox" checked={optedIn} onChange={(event) => setOptedIn(event.target.checked)} /> I agree to share only these anonymous outcome details to improve Momo.</label><small>Public Momo win sharing is paused while the ticker uses demo examples. This form only contributes private anonymous learning data.</small><button className="secondary" type="submit">Share anonymous outcome</button>{message && <p className="insight-message" role="status">{message}</p>}</form></section>;
}
